/**
 * HTML formatter — outputs the report as a self-contained HTML document.
 *
 * The output is a complete page with inlined CSS and no external requests, so it can be
 * written to a file, attached to an email, or published as a static artifact from CI.
 * All interpolated values (author names, emails, file paths) come from git history and are
 * therefore untrusted, so every one of them is escaped before it reaches the markup.
 */

import type { DeveloperReport } from "../developer.js";
import type { TeamReport } from "../team.js";
import type { BoardReport } from "../board.js";

/** Escape a value for safe interpolation into HTML text or a quoted attribute. */
function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

const STYLES = `
  :root {
    color-scheme: light dark;
    --bg: #ffffff;
    --surface: #f4f6f8;
    --border: #d5dae0;
    --text: #16191f;
    --text-muted: #5a6572;
    --accent: #0b5cad;
    --healthy: #1a6c3a;
    --warning: #8a5300;
    --degraded: #a41d1d;
  }
  @media (prefers-color-scheme: dark) {
    :root {
      --bg: #16191f;
      --surface: #21262e;
      --border: #3b424c;
      --text: #f2f4f6;
      --text-muted: #b3bac2;
      --accent: #7cb7f2;
      --healthy: #7cd6a0;
      --warning: #e8bd6d;
      --degraded: #f09a9a;
    }
  }
  * { box-sizing: border-box; }
  body {
    margin: 0;
    padding: 2rem 1.25rem 3rem;
    background: var(--bg);
    color: var(--text);
    font: 16px/1.55 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
  }
  main { max-width: 60rem; margin: 0 auto; }
  h1 { font-size: 1.6rem; margin: 0 0 0.35rem; }
  h2 { font-size: 1.15rem; margin: 2rem 0 0.75rem; }
  .meta { color: var(--text-muted); margin: 0; font-size: 0.95rem; }
  .cards {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(13rem, 1fr));
    gap: 0.75rem;
    margin-top: 1.5rem;
    padding: 0;
    list-style: none;
  }
  .card {
    background: var(--surface);
    border: 1px solid var(--border);
    border-radius: 8px;
    padding: 0.9rem 1rem;
  }
  .card dt { font-size: 0.85rem; color: var(--text-muted); margin: 0 0 0.3rem; }
  .card dd { font-size: 1.5rem; font-weight: 600; margin: 0; }
  .card .sub { display: block; font-size: 0.8rem; font-weight: 400; color: var(--text-muted); margin-top: 0.2rem; }
  table { width: 100%; border-collapse: collapse; font-size: 0.95rem; }
  caption { text-align: left; color: var(--text-muted); font-size: 0.85rem; padding-bottom: 0.4rem; }
  th, td { text-align: left; padding: 0.5rem 0.6rem; border-bottom: 1px solid var(--border); }
  thead th { background: var(--surface); font-size: 0.85rem; text-transform: uppercase; letter-spacing: 0.02em; }
  td.num, th.num { text-align: right; font-variant-numeric: tabular-nums; }
  td.path { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; font-size: 0.85rem; word-break: break-all; }
  .bar { display: block; height: 6px; margin-top: 0.3rem; background: var(--border); border-radius: 3px; overflow: hidden; }
  .bar > span { display: block; height: 100%; background: var(--accent); }
  .badge {
    display: inline-block;
    padding: 0.15rem 0.6rem;
    border-radius: 999px;
    font-size: 0.85rem;
    font-weight: 600;
    border: 1px solid currentColor;
  }
  .badge.healthy { color: var(--healthy); }
  .badge.warning { color: var(--warning); }
  .badge.degraded { color: var(--degraded); }
  ul.notes { margin: 0.75rem 0 0; padding-left: 1.2rem; }
  ul.notes li { margin-bottom: 0.35rem; }
  footer { margin-top: 2.5rem; color: var(--text-muted); font-size: 0.8rem; }
`;

/** Wrap page content in a complete, self-contained HTML document. */
function page(title: string, metaLines: string[], body: string): string {
  const meta = metaLines
    .map((line) => `      <p class="meta">${line}</p>`)
    .join("\n");

  return `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${escapeHtml(title)}</title>
    <style>${STYLES}</style>
  </head>
  <body>
    <main>
      <h1>${escapeHtml(title)}</h1>
${meta}
${body}
      <footer>Generated by kiro-metrics from git commit attribution data.</footer>
    </main>
  </body>
</html>`;
}

function formatPeriod(period: { since: string; until: string }): string {
  return `${escapeHtml(period.since.slice(0, 10))} to ${escapeHtml(period.until.slice(0, 10))}`;
}

/** A metric card. `value` and `sub` must already be escaped or numeric. */
function card(label: string, value: string, sub?: string): string {
  const subHtml = sub ? `<span class="sub">${sub}</span>` : "";
  return `        <div class="card">
          <dt>${escapeHtml(label)}</dt>
          <dd>${value}${subHtml}</dd>
        </div>`;
}

function cards(items: string[]): string {
  return `      <dl class="cards">\n${items.join("\n")}\n      </dl>`;
}

/** Percentage bar. Decorative only — the numeric value is always rendered as text too. */
function bar(rate: number): string {
  const clamped = Math.max(0, Math.min(100, rate));
  return `<span class="bar" aria-hidden="true"><span style="width: ${clamped}%"></span></span>`;
}

interface TableSpec {
  caption: string;
  headers: Array<{ label: string; numeric?: boolean }>;
  /** Cell contents must already be escaped. */
  rows: Array<Array<{ html: string; numeric?: boolean; path?: boolean }>>;
}

function table({ caption, headers, rows }: TableSpec): string {
  const head = headers
    .map(
      (h) =>
        `<th scope="col"${h.numeric ? ' class="num"' : ""}>${escapeHtml(h.label)}</th>`
    )
    .join("");

  const body = rows
    .map((cells) => {
      const tds = cells
        .map((cell, index) => {
          const classes = [
            cell.numeric ? "num" : "",
            cell.path ? "path" : "",
          ]
            .filter(Boolean)
            .join(" ");
          const attr = classes ? ` class="${classes}"` : "";
          // First column acts as the row label for screen readers.
          const tag = index === 0 ? "th" : "td";
          const scope = index === 0 ? ' scope="row"' : "";
          return `<${tag}${scope}${attr}>${cell.html}</${tag}>`;
        })
        .join("");
      return `          <tr>${tds}</tr>`;
    })
    .join("\n");

  return `      <table>
        <caption>${escapeHtml(caption)}</caption>
        <thead>
          <tr>${head}</tr>
        </thead>
        <tbody>
${body}
        </tbody>
      </table>`;
}

export function formatDeveloperHtml(report: DeveloperReport): string {
  const sections: string[] = [];

  sections.push(
    cards([
      card("Total commits", String(report.commits.total)),
      card(
        "AI-involved commits",
        `${report.commits.involvementRate}%`,
        `${report.commits.aiInvolved} of ${report.commits.total} commits${bar(report.commits.involvementRate)}`
      ),
      card(
        "AI-authored lines",
        `${report.lines.authorshipRate}%`,
        `${report.lines.ai.toLocaleString()} of ${report.lines.total.toLocaleString()} lines${bar(report.lines.authorshipRate)}`
      ),
    ])
  );

  if (report.topAiFiles.length > 0) {
    sections.push("      <h2>Top AI-authored files</h2>");
    sections.push(
      table({
        caption: "Files ranked by share of AI-authored lines.",
        headers: [{ label: "File" }, { label: "AI authorship", numeric: true }],
        rows: report.topAiFiles.slice(0, 10).map((file) => [
          { html: escapeHtml(file.file), path: true },
          { html: `${file.authorshipRate}%`, numeric: true },
        ]),
      })
    );
  }

  const email = report.email ? ` (${escapeHtml(report.email)})` : "";

  return page(
    "AI Attribution Report — Developer View",
    [`Author: ${escapeHtml(report.author)}${email}`, `Period: ${formatPeriod(report.period)}`],
    sections.join("\n")
  );
}

export function formatTeamHtml(report: TeamReport): string {
  const sections: string[] = [];

  sections.push(
    cards([
      card(
        "AI code involvement rate",
        `${report.summary.involvementRate}%`,
        `${report.summary.aiInvolvedCommits} of ${report.summary.totalCommits} commits${bar(report.summary.involvementRate)}`
      ),
      card(
        "AI code authorship rate",
        `${report.summary.authorshipRate}%`,
        `share of lines${bar(report.summary.authorshipRate)}`
      ),
      card(
        "Delivery frequency",
        String(report.summary.deliveryFrequency),
        "commits per week"
      ),
      card("Total commits", String(report.summary.totalCommits)),
    ])
  );

  if (report.byAuthor.length > 0) {
    sections.push("      <h2>By author</h2>");
    sections.push(
      table({
        caption: "Per-contributor involvement and authorship rates.",
        headers: [
          { label: "Author" },
          { label: "Involvement", numeric: true },
          { label: "Authorship", numeric: true },
          { label: "Commits", numeric: true },
        ],
        rows: report.byAuthor.map((author) => [
          { html: escapeHtml(author.author) },
          { html: `${author.involvementRate}%`, numeric: true },
          { html: `${author.authorshipRate}%`, numeric: true },
          { html: String(author.commits), numeric: true },
        ]),
      })
    );
  }

  if (report.topAiFiles.length > 0) {
    sections.push("      <h2>Top AI-authored files</h2>");
    sections.push(
      table({
        caption: "Files ranked by share of AI-authored lines.",
        headers: [{ label: "File" }, { label: "AI authorship", numeric: true }],
        rows: report.topAiFiles.slice(0, 10).map((file) => [
          { html: escapeHtml(file.file), path: true },
          { html: `${file.authorshipRate}%`, numeric: true },
        ]),
      })
    );
  }

  if (report.weeklyTrend.length > 0) {
    sections.push("      <h2>Weekly trend</h2>");
    sections.push(
      table({
        caption: "Involvement and authorship rates by week.",
        headers: [
          { label: "Week starting" },
          { label: "Involvement", numeric: true },
          { label: "Authorship", numeric: true },
          { label: "Commits", numeric: true },
        ],
        rows: report.weeklyTrend.map((week) => [
          { html: escapeHtml(week.weekStart) },
          { html: `${week.involvementRate}%`, numeric: true },
          { html: `${week.authorshipRate}%`, numeric: true },
          { html: String(week.commitCount), numeric: true },
        ]),
      })
    );
  }

  return page(
    "AI Attribution Report — Team View",
    [`Period: ${formatPeriod(report.period)}`],
    sections.join("\n")
  );
}

export function formatBoardHtml(report: BoardReport): string {
  const sections: string[] = [];

  const headlineCards = [
    card(
      "AI code involvement",
      `${report.headline.involvementRate}%`,
      `of commits${bar(report.headline.involvementRate)}`
    ),
    card(
      "AI code authorship",
      `${report.headline.authorshipRate}%`,
      `of lines${bar(report.headline.authorshipRate)}`
    ),
    card(
      "Delivery frequency",
      String(report.headline.deliveryFrequency),
      "units per week"
    ),
  ];

  if (report.headline.ctsSwProxy !== undefined) {
    headlineCards.push(
      card(
        "CTS-SW proxy",
        `$${report.headline.ctsSwProxy}`,
        "per delivery unit"
      )
    );
  }

  sections.push(cards(headlineCards));

  const sign = (value: number): string => (value >= 0 ? "+" : "");
  sections.push("      <h2>Trend</h2>");
  sections.push(
    table({
      caption: "Change from the first week to the last week in the period.",
      headers: [{ label: "Metric" }, { label: "Change", numeric: true }],
      rows: [
        [
          { html: "Involvement" },
          {
            html: `${sign(report.trend.involvementChange)}${report.trend.involvementChange}pp`,
            numeric: true,
          },
        ],
        [
          { html: "Authorship" },
          {
            html: `${sign(report.trend.authorshipChange)}${report.trend.authorshipChange}pp`,
            numeric: true,
          },
        ],
      ],
    })
  );

  const status = report.guardrails.status;
  const notes = report.guardrails.notes
    .map((note) => `        <li>${escapeHtml(note)}</li>`)
    .join("\n");

  sections.push("      <h2>Guardrails</h2>");
  sections.push(
    `      <p><span class="badge ${status}">Status: ${escapeHtml(status)}</span></p>`
  );
  sections.push(`      <ul class="notes">\n${notes}\n      </ul>`);

  return page(
    "AI Metrics — Board Summary",
    [`Period: ${formatPeriod(report.period)}`],
    sections.join("\n")
  );
}
